# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GranBlueModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('level', models.IntegerField(max_length=3)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
    ]
