# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GranBlueModel', '0002_boss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tiamat',
        ),
        migrations.AlterField(
            model_name='boss',
            name='level',
            field=models.IntegerField(),
        ),
    ]
