# Generated by Django 2.1 on 2018-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Granblue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('level', models.IntegerField()),
                ('code', models.CharField(max_length=8)),
            ],
        ),
    ]
